version: '3.7'

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - 8000
  app-node:
    depends_on:
      - dynamodb-local
    image: banst/awscli
    environment:
      AWS_ACCESS_KEY_ID: 'AKIAI44QH8DHBEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'je7MtGbClwBF/2Zp9Utk/h3yCo8nvbEXAMPLEKEY'
    command: dynamodb list-tables --endpoint-url http://dynamodb-local:8000 --region us-west-2
